FROM golang:1.16.5-alpine3.13 as goBuilder
RUN apk add --no-cache bash
RUN mkdir -p /generator-build
WORKDIR /generator-build
COPY . .
RUN /bin/bash -c 'if [ ! -e ".env" ]; then  echo "env file not found" ;  exit 1  ; else echo "check env file success" ; exit 0; fi '
WORKDIR /generator-build/app/console/prediction-generator
RUN go build -o lottery-generator

FROM alpine:latest
RUN apk add tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN mkdir -p /generator
WORKDIR /generator
COPY --from=goBuilder /generator-build/app/console/prediction-generator/lottery-generator .
COPY --from=goBuilder /generator-build/.env .
ENTRYPOINT ["./lottery-generator"]
